### PR TITLE
Add fastapi helloworld

### PR DESCRIPTION
**Pull request by pozsa**
Just adding a minimalist setup so we can test the basics of the CI
pipeline.

### CODE REVIEW

**Comment by pozsa** [comment]
hmm.. this is annoying, there's no official way to feed your dependencies to super-linter.
Any thoughts on what should we do?

**Comment by pozsa** [comment]
I found a hacky way to inject our dependencies.
https://github.com/github/super-linter/issues/157#issuecomment-648850330

**Comment by minottic** [comment]
I guess this needs #42 before review?

**Comment by pozsa** [comment]
and I want to merge #35 before this as well

**Review by minottic — APPROVED** [review]

**Pull request merged**
