### PR TITLE
Connect the app to postgres

### PR DESCRIPTION
**Pull request by pozsa**
Using 2.0 sqlalchemy style for future compatibility.
The `get_db` function can be used as a dependency to inject a working
db session where it will be needed.

### CODE REVIEW

**Comment by pozsa** [comment]
@minottic wow.. I didn't expect codecov to detect that coverage drop :D
do we want 100% coverage? (I could get the coverage although the test would probably only check the type of information returned cause I don't see a way of getting the values right.)

**Comment by minottic** [comment]
yes, I think the type or the fact that they are > 0

**Comment by pozsa** [comment]
I was testing this locally.. I believe we are running into this problem
https://github.com/nedbat/coveragepy/issues/1082

If I run `coverage run --concurrency=thread,greenlet --source=app -m pytest` without any changes to the current code the reported coverage is 100%

I don't see an option to use the concurrency flag with `pytest-cov` though.

Should I just change the command to run the tests in the pipeline?

**Comment by pozsa** [comment]
@minottic what do you think?

**Review by minottic — APPROVED** [review]

**Review by minottic — APPROVED** [review]

**Comment by minottic** [comment]
sorry I did not realise until now it is out of date. I will re-review once updated

**Pull request merged**
